In [2]:
import matplotlib
import networkx as nx
import matplotlib.pyplot as plt
import random
import numpy as np
import pandas as pd
import os
from concurrent.futures import ProcessPoolExecutor

In [27]:
# === Parameters ===
adjlist = '../ER-1000'
static_graph = nx.read_adjlist(f"{adjlist}.txt", nodetype=int)
N = static_graph.number_of_nodes()
static_edges_set = set(static_graph.edges())

m_values = [0, 15]
activity = 0.1
activity_rates = {node: activity for node in static_graph.nodes}

timesteps = 200
num_runs = 100

beta = 0.08
mu = 1

m_list   = np.arange(0, 12, 1)                     # m = 0,2,4,...,40
tau_list = np.round(np.arange(0.15, 0.25, 0.006), 3)  # tau sweep

transient_cutoff = 100
initial_infected_ratio = 0.01

csv_file = "sis_summary_results.csv"


A = nx.to_numpy_array(static_graph, dtype=int)
eigenvalues, _ = np.linalg.eig(A)
lambda_max_A = np.max(eigenvalues)
tau_c = 1 / lambda_max_A
tau = beta/mu
# theoretical m_c (float) and rounded integer m_c for use in simulations
m_c_float = ((1 / tau) - (lambda_max_A)) / (2*activity)
m_c = int(round(m_c_float))

m_c, tau_c, lambda_max_A

(7, np.float64(0.09037413198505428), np.float64(11.06511319152007))

In [29]:
m_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
tau_list

array([0.15 , 0.156, 0.162, 0.168, 0.174, 0.18 , 0.186, 0.192, 0.198,
       0.204, 0.21 , 0.216, 0.222, 0.228, 0.234, 0.24 , 0.246])

In [8]:
m_list   = np.arange(6, 7, 1, dtype=int)  

m_list

array([6])

In [11]:
tau_list = np.round(np.arange(0.09, 0.091, 0.005), 3)

tau_list

array([0.09])